### ISSUE TITLE
Typo at page 121

### ISSUE THREAD

**Issue by Lu-UofT** [siefkenj/IBLLinearAlgebra#109]
File: linearalgebra-book.pdf, **2019/10/27 Edition**
Physical Page Number: **121**
Typo: please refer to the attached picture.
![typo P121](https://user-images.githubusercontent.com/29336724/68974343-82ed6c80-07be-11ea-8606-fc92a32ff2d0.png)

**Comment by siefkenj** [comment]
Thanks, fixed!
