### ISSUE TITLE
Typo at Page 164

### ISSUE THREAD

**Issue by Lu-UofT** [siefkenj/IBLLinearAlgebra#110]
File: linearalgebra-book.pdf, **2019/10/27 Edition**
Physical Page Number: **164**
Typo: please refer to the attached picture.

![typo_p164](https://user-images.githubusercontent.com/29336724/68974578-16bf3880-07bf-11ea-9af0-dd018e1af6f7.png)

**Comment by siefkenj** [comment]
Fixed :-)
