### ISSUE TITLE
Potential better clarification at Page 141

### ISSUE THREAD

**Issue by Lu-UofT** [siefkenj/IBLLinearAlgebra#111]
File: linearalgebra-book.pdf, **2019/10/27 Edition**
Physical Page Number: **141**
Suggestion: In class, you have clarified that this matrix M is not the same induced matrix of T.
But it would be less confusing for me to change "n x m matrix M" to "m x n matrix M". See the attached picture. Thanks.
![suggestion_page141](https://user-images.githubusercontent.com/29336724/68974966-fe9be900-07bf-11ea-8138-a3d70c228951.png)

**Comment by siefkenj** [comment]
Changed :-)
