### ISSUE TITLE
Error in the Instructors guide

### ISSUE THREAD

**Issue by billwang115** [siefkenj/IBLLinearAlgebra#155]
There is a typo to the solution to 25.4 on page 33 in the instructors guide. The final answer should be arccos(7/2sqrt(6)) instead of arccos(3/2sqrt(6)).

![image](https://user-images.githubusercontent.com/23006620/82503037-82fc5b00-9ac6-11ea-8c9b-25600cda4947.png)

**Comment by luema** [comment]
@billwang115 Hi, there is no mistake :)
I believe you were looking at the fifth math line as though there were a zero on the left-hand side, rather than a four.
