### ISSUE TITLE
Typo on page 94

### ISSUE THREAD

**Issue by billwang115** [siefkenj/IBLLinearAlgebra#156]
There's a typo in the section about "The Row Picture" on page 94. It should say "-21" instead of "-12" when it is mentionning the dot product with r_2.

![image](https://user-images.githubusercontent.com/23006620/82618893-56b60c80-9ba2-11ea-9109-e5160fdd737d.png)

**Comment by siefkenj** [comment]
Thanks for finding these errors! I'll fix them soon.

Do you know how to make a pull request? You could fix the typos directly and then add your name to the "Contributors" list.

**Comment by billwang115** [comment]
Oh didn't know about that feature. I'll just do that next time. Thanks.

**Comment by siefkenj** [comment]
Fixed!
