### ISSUE TITLE
Consider using GitHub pages for hosting pdfs

### ISSUE THREAD

**Issue by lukepereira** [siefkenj/IBLLinearAlgebra#182]
I noticed the pdf renderer on GitHub can be slow for large files. It might be better to use the browser's pdf viewer, which can be done by enabling GitHub pages. 

In the repo, update `Settings > GitHub Pages > Source > master`. Then view the book at http://siefkenj.github.io/IBLLinearAlgebra/dist/linearalgebra-book.pdf

**Comment by siefkenj** [comment]
You can already view the book at https://github.com/siefkenj/IBLLinearAlgebra/raw/master/dist/linearalgebra-book.pdf

**Comment by lukepereira** [comment]
A hosted version would contain the most up-to-date version whereas the downloaded pdf would become out of date
