### ISSUE TITLE
There is a typo on the solution for Module 5, Question 4

### ISSUE THREAD

**Issue by RealFakeAccount** [siefkenj/IBLLinearAlgebra#199]
> Geometrically, T is a filled in triangle with vectices

vectices should be vertices.

**Comment by RealFakeAccount** [comment]
![image](https://user-images.githubusercontent.com/63186767/95002119-9e13c700-059e-11eb-831d-00da2c044fb4.png)

**Comment by RealFakeAccount** [comment]
BTW, if I found other typo, may I just create a pull request?

**Comment by siefkenj** [comment]
Yes, please!
