### ISSUE TITLE
Page 6

### ISSUE THREAD

**Issue by aanas1010** [siefkenj/IBLLinearAlgebra#205]
![image](https://user-images.githubusercontent.com/77357622/104362526-e74ead80-54e1-11eb-8fc9-572fdaae7768.png)

If I'm not mistaken, the vector, v, is supposed to be x and y. But when demonstrating scalar multiplication, a and b are used instead

**Comment by siefkenj** [comment]
Good catch!

**Comment by siefkenj** [comment]
Fixed :-)
