### ISSUE TITLE
Solution for Module 11 Q5d formatting

### ISSUE THREAD

**Issue by ifaz-alam** [siefkenj/IBLLinearAlgebra#208]
![image](https://user-images.githubusercontent.com/45114241/112737262-7ee36a00-8f2f-11eb-933d-a92d711855bf.png)

**Comment by siefkenj** [comment]
Good find! Do you know LaTeX? Are you able to make a PR?

**Comment by ifaz1106** [comment]
Yes, I have submitted a pull request!

**Comment by siefkenj** [comment]
Fixed in #209
