### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by asdasdasdasd1234** [siefkenj/IBLLinearAlgebra#213]
Have seen a few but: 

- Module 11, Range & Nullspace. This chapter is all over the place. That said, in the proof of the Theorem (Row-Column Dimension) on p. 130, the first line of the proof uses rank(A) = rank (A^T) when the concept of rank as applied to a matrix, and not an LT, hasn't even been introduced in the book at this point.

**Comment by siefkenj** [comment]
Thank you for your comment. The proof on page 130 has been updated :-).

What are the other mistakes that you noticed?

**Comment by siefkenj** [comment]
Thank you for your comments. I will take them under consideration.
