### ISSUE TITLE
Convoluted solution to an example problem

### ISSUE THREAD

**Issue by phro** [siefkenj/IBLLinearAlgebra#215]
The second example after the definition of linear dependence (geometric) involves a roundabout method of building a set, then using unconventional reasoning to justify why it is linearly dependent. It would be more straightforward to simply create two systems of equations and solve them (one has a solution immediately upon inspection, and the second requires slightly more work).

**Comment by siefkenj** [comment]
Will be fixed in the next update! This one is tricky since Module 2 solves this question using systems of equations. The point of this example is to use linear independence/dependence to answer the same question a different way.
