### ISSUE TITLE
Appendix 5 solution error

### ISSUE THREAD

**Issue by rzwang0** [siefkenj/IBLLinearAlgebra#230]
On page 260, the Solutions for Appendix 1 section writes the system of linear equations for question 5c (iii) as
```math
\displaystyle{\displaylines{\begin{equation*}
\left\{
\begin{alignedat}{2}
 x & +{} &  y & = 42 \\
  & {} &  y & = 77
\end{alignedat}
\right.
\end{equation*}}}
``` 
which is incorrect. Instead, the system should be
```math
\displaystyle{\displaylines{\begin{equation*}
\left\{
\begin{alignedat}{2}
 x & +{} &  y & = 42 \\
 2x & +{} &  4y & = 77
\end{alignedat}
\right.
\end{equation*}}}
``` 
which would reduce to
```math
\displaystyle{\displaylines{\begin{equation*}
\left\{
\begin{alignedat}{2}
 x & +{} &  y & = 42 \\
  & {} &  y & = -\frac{7}{2}
\end{alignedat}
\right.
\end{equation*}}}
```
after row reduction as shown in the textbook (this part of the solution is correct).

**Comment by rzwang0** [comment]
Unfortunately, I don't know how to make a pull request.

**Comment by siefkenj** [comment]
If you click the little edit button in the upper right of https://github.com/siefkenj/IBLLinearAlgebra/blob/master/book/modules/appendix1-exercises.tex you should be able to make a change and submit that as a pull request.

Let me know if you have trouble figuring it out.

**Comment by rzwang0** [comment]
I submitted a pull request. Thank you for your help.

**Comment by siefkenj** [comment]
Thanks for finding these!
