### ISSUE TITLE
Error - Appendix 5 - Practical Problem Solutions

### ISSUE THREAD

**Issue by xiaoyaojudy** [siefkenj/IBLLinearAlgebra#243]
On page 267, Solutions for Appendix 4, 2(c),
 
I think the answer should be 5 instead of 21.

Justification:
det = (-1)(-3)(-1)+(0)(-8)(1)+(-8)(1)(-2)-(0)(1)(-1)-(-1)(-8)(-2)-(-8)(-3)(1)
       = (-3)+(0)+(16)-(0)-(-16)-(24)
       =(-3)+16+16-24
       = 5
Please correct me if wrong.

Thanks you!

**Comment by siefkenj** [comment]
You're absolutely right! I will fix this in the next update :-)
