### ISSUE TITLE
Typo in example on page 6

### ISSUE THREAD

**Issue by gabbynozaki** [siefkenj/IBLLinearAlgebra#83]
https://github.com/siefkenj/IBLLinearAlgebra/blob/ed10b23b4014a47223242217953eaf81cb6e36de/problemsets-mat223/modules/module1.tex#L535

For the example at the bottom of page 6, line 535, should the answer be 2e1 + 12e2 + **5**e3?

**Comment by siefkenj** [comment]
Good catch! Can you make a PR that fixes this typo?

**Comment by siefkenj** [comment]
I have fixed this typo. Thanks!
