### ISSUE TITLE
page 23 example

### ISSUE THREAD

**Issue by Shujie1024** [siefkenj/IBLLinearAlgebra#84]
According to the answer of the example, vector b should be [1 -1], not [-1 1].

**Comment by siefkenj** [comment]
Thanks for finding this! Are you able to point out the line number in the source code? You can find the modules here: https://github.com/siefkenj/IBLLinearAlgebra/tree/master/problemsets-mat223/modules   If you click a line and then click the "..." that appears on the left, you can select "Copy permalink". That will be a direct link to that line in the file.

**Comment by Shujie1024** [comment]
Hi Siefken,
The link to the code is:
https://github.com/siefkenj/IBLLinearAlgebra/blob/a342d22574ab1d84e6fa1d8cb3a97d36216b8a9d/problemsets-mat223/modules/module2.tex#L657
It's in Module 2, line 657.
Hope that will help you!

Regards,
Shujie Deng

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by siefkenj** [comment]
I have fixed this typo. Thanks!
