### ISSUE TITLE
Potential wording issue (minor)

### ISSUE THREAD

**Issue by chriskorosu** [siefkenj/IBLLinearAlgebra#85]
https://github.com/siefkenj/IBLLinearAlgebra/blob/dfe3ed3a343e0ff88100d955dadccc55c81f1dc1/problemsets-mat223/modules/module1.tex#L286

I think the phrase "scaled up by $\alpha$" is inaccurate when $0 < \alpha < 1$, since the vector will actually be scaled down in that case. 

So perhaps this should be "scaled by $\alpha$" (with the "up" omitted), or "scaled up or down by $\alpha$".

**Comment by siefkenj** [comment]
Good find :-). I'll remove the "up".
