### ISSUE TITLE
Typo Page 37

### ISSUE THREAD

**Issue by TimSquire** [siefkenj/IBLLinearAlgebra#87]
There is a typo on page 37 of the MAT223 Workbook in the first "Example" given on the page. On the line which starts by saying "By inspection, we see ...", it then goes on to say vector c = 2(vector a) when it should say vector c = 2(vector b). See image below 

<img width="467" alt="Capture" src="https://user-images.githubusercontent.com/55571586/65299870-4a733e80-db3f-11e9-9d4c-4fab54c0f44d.PNG">

**Comment by siefkenj** [comment]
Thanks. Fixed!
