### ISSUE TITLE
 a missing vector and a few typos at page#41 in the textbook

### ISSUE THREAD

**Issue by Lu-UofT** [siefkenj/IBLLinearAlgebra#90]
**File:** linearalgebra-book.pdf, 2019/09/11 Edition
**Physical Page Number:** 41

**Practice Problem#7:** I think the vector p is missed from the equation (see picture in below)
<img width="681" alt="page41_missed-vector" src="https://user-images.githubusercontent.com/29336724/65394488-d2825f80-dd5c-11e9-9704-e4955efb6dd1.png">

**Practice Problem#11:** Typos in a), b) and c). It should be "dependent" rather than "dependant"

**Comment by siefkenj** [comment]
Thanks. Fixed!
