### ISSUE TITLE
typos in page 71

### ISSUE THREAD

**Issue by Lu-UofT** [siefkenj/IBLLinearAlgebra#91]
**File:** linearalgebra-book.pdf, 2019/10/08 Edition
**Physical Page Number:** 71
**Typos:** please refer to the attached picture.
![typos_page71](https://user-images.githubusercontent.com/29336724/66770410-95098180-ee85-11e9-807d-b3bfbda67926.png)

**Comment by siefkenj** [comment]
Thanks! It's been fixed :-)
